### ISSUE TITLE
Divide by zero error when using the "AlternateColors" config option

### ISSUE THREAD

**Issue by aloussase** [tomlazar/table#8]
I get a panic with divide by zero error when using the "AleternateColors" option. Here is the error:

![image](https://user-images.githubusercontent.com/84427521/163475939-0f7b4ddb-4afa-41db-b3de-bcceaf9e577e.png)

**Comment by tomlazar** [comment]
Should be fixed as of [v0.1.2](https://github.com/tomlazar/table/releases/tag/v0.1.2), but you should keep in mind if your not passing in a value for the [Config.AltColorCodes](https://github.com/tomlazar/table/blob/main/table.go#L18=) value it won't know what colors to alternate between, you can use the [Default](https://github.com/tomlazar/table/blob/main/table.go#L23=) values if you want some simple settings.
